import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ResponsiveDrawer } from '@/app/components/core/SidebarComponent'
import "./globals.css";
import { SidebarComponent } from "./components/core/SidebarComponent";
import { ThemeProvider } from "@mui/material";
import { LigthTheme } from "./theme/ligth";
import { DarkTheme } from "./theme/dark";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <ThemeProvider theme={DarkTheme} >
      <body className={inter.className}>
        {children}
      </body>
      </ThemeProvider>
    </html>
  );
}
