import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ResponsiveDrawer } from '@/app/components/core/SidebarComponent'
import "./globals.css";
import { SidebarComponent } from "./components/core/SidebarComponent";
import { Box, ThemeProvider } from "@mui/material";
import { LigthTheme } from "./theme/ligth";
import { DarkTheme } from "./theme/dark";
import { ThemeComponent } from "./components/core/ThemeComponent";
import { ThemeProviderComponent } from "./theme/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProviderComponent>
      <Box component={'html'} lang="es" bgcolor={'background.default'} >
        <body>
          <Box bgcolor={'Background'}>
            <SidebarComponent/>
            {children}
          </Box>
        </body>
      </Box>
    </ThemeProviderComponent>
  );
}
